lighttpd: fix EXTRA_OECONF
* --without-memcache was renamed to --without-memcached in:
  https://redmine.lighttpd.net/projects/lighttpd/repository/revisions/f3b577ddee36b9555331dfbcddb6a200df2ba438
* causing:
  ERROR: lighttpd-1.4.41-r0 do_configure: QA Issue: lighttpd: configure was passed unrecognised options: --without-memcache [unknown-configure-option]

(From OE-core rev: d53b220205259705649cb7741a21cb267519d565)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>